{
  "formatVersion": "1.1",
  "component": {
    "group": "io.grpc",
    "module": "grpc-kotlin-stub",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.62.2"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "grpc-kotlin-stub-1.5.0.jar",
          "url": "grpc-kotlin-stub-1.5.0.jar",
          "size": 83890,
          "sha512": "0d953661ab7121d4355ff60e8630dbbc9ba6daf734d4858d8d6b96ed0a740d84e28eddacf8de8a64b45d2994971a8f70edaa50aa2c16cdc21e53c07744794199",
          "sha256": "cc482c0e2f6b588ba90c7152d4aeee27cfee4bde1688326327dc74c6284477f0",
          "sha1": "bcaae7d4ce13b53e61aed980dbc81f72f13d86f0",
          "md5": "7d823f0c77308b67ca4123643f20abb6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.62.2"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "grpc-kotlin-stub-1.5.0.jar",
          "url": "grpc-kotlin-stub-1.5.0.jar",
          "size": 83890,
          "sha512": "0d953661ab7121d4355ff60e8630dbbc9ba6daf734d4858d8d6b96ed0a740d84e28eddacf8de8a64b45d2994971a8f70edaa50aa2c16cdc21e53c07744794199",
          "sha256": "cc482c0e2f6b588ba90c7152d4aeee27cfee4bde1688326327dc74c6284477f0",
          "sha1": "bcaae7d4ce13b53e61aed980dbc81f72f13d86f0",
          "md5": "7d823f0c77308b67ca4123643f20abb6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grpc-kotlin-stub-1.5.0-sources.jar",
          "url": "grpc-kotlin-stub-1.5.0-sources.jar",
          "size": 12468,
          "sha512": "c54c25344bac5dfd1c21afc8e682b8e8a00748c27ab9d3ac2a8e9efe5c53fa4809dc0fdd93267efb77f46c0abf61403dc908a460e2603c76084ebac6cad41508",
          "sha256": "9dc65b16db7467661094ef4ca32c6efa86324dfdbc4cb2a4348b6fb4b8a5b533",
          "sha1": "2fbf5e572fdc0d376fa134e4c716f372820cf10a",
          "md5": "2c6dccc93a31ce8f5e3bb8a02fe707ba"
        }
      ]
    }
  ]
}
