/* DO NOT EDIT THIS FILE - it is machine generated (Manually recreated for migration) */
/**
 * @author android_zero
 * 定义了 Java 层 TSLanguageCss.Native 类中 native 方法的元数据和注册逻辑。
 */

#include <jni.h>
#include "ts__log.h"

#ifndef __TS_LOG_DEBUG
#ifdef NDEBUG
#define __TS_LOG_DEBUG 0
#else
#define __TS_LOG_DEBUG 1
#endif
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_css_TSLanguageCss__Native_METHODS
#define _Included_com_itsaky_androidide_treesitter_css_TSLanguageCss__Native_METHODS

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com.itsaky.androidide.treesitter.css.TSLanguageCss.Native
 * Method:    getInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_css_TSLanguageCss_00024Native_getInstance
  (JNIEnv *env, jclass clazz);

#ifdef __cplusplus
}
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_css_TSLanguageCss__Native_METHOD_SIGNATURES
#define _Included_com_itsaky_androidide_treesitter_css_TSLanguageCss__Native_METHOD_SIGNATURES

// Index of method getInstance of class com.itsaky.androidide.treesitter.css.TSLanguageCss.Native in _TSLanguageCss_Native_METHODS array
#define TSLanguageCss_Native_getInstance__ARR_IDX 0

/*
 * Class:     com.itsaky.androidide.treesitter.css.TSLanguageCss.Native
 * Method:    getInstance
 * Signature: ()J
 */
static JNINativeMethod TSLanguageCss_Native_getInstance= {
    .name = "getInstance",
    .signature = "()J",
    .fnPtr = nullptr
};


// This function is called in order to set the actual
// implementations of the native methods defined in class 
// com/itsaky/androidide/treesitter/css/TSLanguageCss$Native
void TSLanguageCss_Native_SetJniMethods(JNINativeMethod *methods, int count);

// Number of elements in _TSLanguageCss_Native_METHODS
#define _TSLanguageCss_Native_METHOD_COUNT 1
// All native methods in class com/itsaky/androidide/treesitter/css/TSLanguageCss$Native
#define TSLanguageCss_Native_DefMethodsArray \
    JNINativeMethod _TSLanguageCss_Native_METHODS[] = { \
        TSLanguageCss_Native_getInstance, \
    };

#ifndef SET_JNI_METHOD
#define SET_JNI_METHOD(_mths, _mth, _func) { \
    void *ptr = (void *)(&_func); \
    (_mths + _mth##__ARR_IDX)->fnPtr = ptr; \
    if (__TS_LOG_DEBUG == 1) { \
        LOGD(LOG_TAG, "SET_JNI_METHOD: %s to %p", _mth.name, ptr); \
        LOGD(LOG_TAG, "SET_JNI_METHOD: fnPtr = %p", _mths[_mth##__ARR_IDX].fnPtr); \
    } \
}
#endif


// Registers the native methods of class com/itsaky/androidide/treesitter/css/TSLanguageCss$Native with the given JNIEnv
#define TSLanguageCss_Native_AutoRegisterNatives(_env) \
    int _TSLanguageCss_Native_rc; \
    TSLanguageCss_Native_SetJniMethods(&_TSLanguageCss_Native_METHODS[0], _TSLanguageCss_Native_METHOD_COUNT); \
    if (__TS_LOG_DEBUG == 1) { \
    for (int i = 0; i < _TSLanguageCss_Native_METHOD_COUNT; ++i) { \
        JNINativeMethod mth = *(_TSLanguageCss_Native_METHODS + i); \
        LOGD(LOG_TAG, "Register native method: '%s', '%s', '%p'", mth.name, mth.signature, mth.fnPtr); } \
    } \
    jclass _TSLanguageCss_Native_class = _env->FindClass("com/itsaky/androidide/treesitter/css/TSLanguageCss$Native"); \
    if (_TSLanguageCss_Native_class == NULL) { \
        LOGE(LOG_TAG, "Failed to find class com/itsaky/androidide/treesitter/css/TSLanguageCss$Native"); \
        return JNI_ERR; \
    } \
    _TSLanguageCss_Native_rc = _env->RegisterNatives(_TSLanguageCss_Native_class, _TSLanguageCss_Native_METHODS, _TSLanguageCss_Native_METHOD_COUNT); \
    if (_TSLanguageCss_Native_rc != JNI_OK) { \
        LOGE(LOG_TAG, "Failed to register native methods for class 'com/itsaky/androidide/treesitter/css/TSLanguageCss$Native'. Result: %d", _TSLanguageCss_Native_rc); \
        return _TSLanguageCss_Native_rc; \
    }\


#endif
#endif