/* DO NOT EDIT THIS FILE - Manually recreated for migration */
/**
 * @author android_zero
 */

#include <jni.h>
#include "ts__log.h"

#ifndef __TS_LOG_DEBUG
#ifdef NDEBUG
#define __TS_LOG_DEBUG 0
#else
#define __TS_LOG_DEBUG 1
#endif
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_php_TSLanguagePhp__Native_METHODS
#define _Included_com_itsaky_androidide_treesitter_php_TSLanguagePhp__Native_METHODS

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_php_TSLanguagePhp_00024Native_getInstance
  (JNIEnv *env, jclass clazz);

JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_php_TSLanguagePhp_00024Native_getPhpOnlyInstance
  (JNIEnv *env, jclass clazz);

#ifdef __cplusplus
}
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_php_TSLanguagePhp__Native_METHOD_SIGNATURES
#define _Included_com_itsaky_androidide_treesitter_php_TSLanguagePhp__Native_METHOD_SIGNATURES

#define TSLanguagePhp_Native_getInstance__ARR_IDX 0
#define TSLanguagePhp_Native_getPhpOnlyInstance__ARR_IDX 1

static JNINativeMethod TSLanguagePhp_Native_getInstance= {
    .name = "getInstance",
    .signature = "()J",
    .fnPtr = nullptr
};

static JNINativeMethod TSLanguagePhp_Native_getPhpOnlyInstance= {
    .name = "getPhpOnlyInstance",
    .signature = "()J",
    .fnPtr = nullptr
};

void TSLanguagePhp_Native_SetJniMethods(JNINativeMethod *methods, int count);

// 方法总数变为 2
#define TSLanguagePhp_Native_METHOD_COUNT 2

#define TSLanguagePhp_Native_DefMethodsArray \
    JNINativeMethod _TSLanguagePhp_Native_METHODS[] = { \
        TSLanguagePhp_Native_getInstance, \
        TSLanguagePhp_Native_getPhpOnlyInstance, \
    };

#ifndef SET_JNI_METHOD
#define SET_JNI_METHOD(_mths, _mth, _func) { \
    void *ptr = (void *)(&_func); \
    (_mths + _mth##__ARR_IDX)->fnPtr = ptr; \
    if (__TS_LOG_DEBUG == 1) { \
        LOGD(LOG_TAG, "SET_JNI_METHOD: %s to %p", _mth.name, ptr); \
        LOGD(LOG_TAG, "SET_JNI_METHOD: fnPtr = %p", _mths[_mth##__ARR_IDX].fnPtr); \
    } \
}
#endif

#define TSLanguagePhp_Native_AutoRegisterNatives(_env) \
    int _TSLanguagePhp_Native_rc; \
    TSLanguagePhp_Native_SetJniMethods(&_TSLanguagePhp_Native_METHODS[0], TSLanguagePhp_Native_METHOD_COUNT); \
    if (__TS_LOG_DEBUG == 1) { \
    for (int i = 0; i < TSLanguagePhp_Native_METHOD_COUNT; ++i) { \
        JNINativeMethod mth = *(_TSLanguagePhp_Native_METHODS + i); \
        LOGD(LOG_TAG, "Register native method: '%s', '%s', '%p'", mth.name, mth.signature, mth.fnPtr); } \
    } \
    jclass _TSLanguagePhp_Native_class = _env->FindClass("com/itsaky/androidide/treesitter/php/TSLanguagePhp$Native"); \
    if (_TSLanguagePhp_Native_class == NULL) { \
        LOGE(LOG_TAG, "Failed to find class com/itsaky/androidide/treesitter/php/TSLanguagePhp$Native"); \
        return JNI_ERR; \
    } \
    _TSLanguagePhp_Native_rc = _env->RegisterNatives(_TSLanguagePhp_Native_class, _TSLanguagePhp_Native_METHODS, TSLanguagePhp_Native_METHOD_COUNT); \
    if (_TSLanguagePhp_Native_rc != JNI_OK) { \
        LOGE(LOG_TAG, "Failed to register native methods for class 'com/itsaky/androidide/treesitter/php/TSLanguagePhp$Native'. Result: %d", _TSLanguagePhp_Native_rc); \
        return _TSLanguagePhp_Native_rc; \
    }\

#endif
#endif