; Automatically generated by Advanced Tree-sitter SCM Generator
; @author android_zero
; This file contains accurate structural contexts based on AST fields.

; ======================================
; Types
; ======================================

(array_type element: (_unannotated_type) @type)
(cast_expression type: (_type) @type)
(field_declaration type: (_unannotated_type) @type)
(formal_parameter type: (_unannotated_type) @type)
(interface_declaration name: (identifier) @type)
(interface_declaration type_parameters: (type_parameters) @type)
(local_variable_declaration type: (_unannotated_type) @type)
(method_declaration type: (_unannotated_type) @type)
(method_declaration type_parameters: (type_parameters) @type)

; ======================================
; Functions
; ======================================

(method_declaration name: (identifier) @function)

; ======================================
; Variables
; ======================================

(assignment_expression left: (identifier) @variable)
(identifier) @variable
(method_declaration parameters: (formal_parameters) @variable.parameter)
(package_declaration name: (identifier) @variable)
(package_declaration name: (scoped_identifier) @variable)
(parcelable_declaration name: (identifier) @variable)
(scoped_identifier name: (identifier) @variable)
(scoped_identifier scope: (identifier) @variable)
(scoped_identifier scope: (scoped_identifier) @variable)
(scoped_identifier) @variable
(scoped_type_identifier) @variable
(single_static_import member: (identifier) @variable)
(single_static_import scope: (identifier) @variable)
(single_static_import scope: (scoped_identifier) @variable)
(static_import_on_demand type_name: (identifier) @variable)
(static_import_on_demand type_name: (scoped_identifier) @variable)
(type_identifier) @variable
(variable_declarator name: (identifier) @variable)

; ======================================
; Properties
; ======================================

(element_value_pair key: (identifier) @property)
(field_access field: (identifier) @property)
(field_access field: (this) @property)

; ======================================
; Literals
; ======================================

(binary_integer_literal) @number
(block_comment) @comment
(boolean_type) @boolean
(comment) @comment
(decimal_floating_point_literal) @number
(decimal_integer_literal) @number
(false) @boolean
(floating_point_type) @number
(hex_floating_point_literal) @number
(hex_integer_literal) @number
(line_comment) @comment
(octal_integer_literal) @number
(string_literal) @string
(true) @boolean

; ======================================
; Attributes
; ======================================

(annotation arguments: (annotation_argument_list) @attribute)
(annotation name: (identifier) @attribute)
(annotation name: (scoped_identifier) @attribute)
(marker_annotation name: (identifier) @attribute)
(marker_annotation name: (scoped_identifier) @attribute)

; ======================================
; Keywords, Operators & Punctuation
; ======================================

; Keywords
[
  "assert"
  "byte"
  "char"
  "class"
  "default"
  "double"
  "extends"
  "float"
  "import"
  "in"
  "inout"
  "int"
  "interface"
  "long"
  "oneway"
  "out"
  "package"
  "parcelable"
  "return"
  "short"
  "static"
  "throws"
  "yield"
] @keyword

; Operators
[
  "!="
  "%"
  "&"
  "&&"
  "*"
  "+"
  "-"
  "/"
  "<"
  "<<"
  "<="
  "="
  "=="
  ">"
  ">="
  ">>"
  ">>>"
  "?"
  "^"
  "|"
  "||"
] @operator

; Brackets
[
  "("
  ")"
  "["
  "]"
  "{"
  "}"
] @punctuation.bracket

; Delimiters
[
  ","
  ":"
  ";"
] @punctuation.delimiter

