// This file is automatically generated. DO NOT EDIT!


/*
 *  This file is part of android-tree-sitter.
 *
 *  android-tree-sitter library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  android-tree-sitter library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *  along with android-tree-sitter.  If not, see <https://www.gnu.org/licenses/>.
 */


#include <jni.h>
#include <tree_sitter/api.h>

#include "ts__onload.h"
#include "ts_typeScript.h"

#ifdef __ANDROID__
static jint JNI_VERSION = JNI_VERSION_1_6;
#else
static jint JNI_VERSION = JNI_VERSION_10;
#endif

// 声明外部入口 (TSX 和 TypeScript)
extern "C" TSLanguage *tree_sitter_typescript();
extern "C" TSLanguage *tree_sitter_tsx();

static jlong TSLanguageTypeScript_getInstance(JNIEnv *env, jclass clazz) {
    return (jlong) tree_sitter_typescript();
}
static jlong TSLanguageTypeScript_getTsxInstance(JNIEnv *env, jclass clazz) {
    return (jlong) tree_sitter_tsx();
}
void TSLanguageTypeScript_Native_SetJniMethods(JNINativeMethod *methods, int count) {
  SET_JNI_METHOD(methods, TSLanguageTypeScript_Native_getInstance, TSLanguageTypeScript_getInstance);
  SET_JNI_METHOD(methods, TSLanguageTypeScript_Native_getTsxInstance, TSLanguageTypeScript_getTsxInstance);
}

JNIEXPORT jint JNI_OnLoad(JavaVM *vm, void *reserved) {
  JNIEnv *env;
  if (vm->GetEnv(reinterpret_cast<void **>(&env), JNI_VERSION) != JNI_OK) return JNI_ERR;
  TS_JNI_ONLOAD__DEFINE_METHODS_ARR
  TS_JNI_ONLOAD__AUTO_REGISTER(env)
  return JNI_VERSION;
}