/* DO NOT EDIT THIS FILE - it is machine generated (Manually recreated for migration) */
/**
 * @author android_zero
 * 定义了 Java 层 TSLanguageTypeScript.Native 类中 native 方法的元数据和注册逻辑。
 */

#include <jni.h>
#include "ts__log.h"

#ifndef __TS_LOG_DEBUG
#ifdef NDEBUG
#define __TS_LOG_DEBUG 0
#else
#define __TS_LOG_DEBUG 1
#endif
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_typeScript_TSLanguageTypeScript__Native_METHODS
#define _Included_com_itsaky_androidide_treesitter_typeScript_TSLanguageTypeScript__Native_METHODS

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com.itsaky.androidide.treesitter.typeScript.TSLanguageTypeScript.Native
 * Method:    getInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_typeScript_TSLanguageTypeScript_00024Native_getInstance
  (JNIEnv *env, jclass clazz);
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_typeScript_TSLanguageTypeScript_00024Native_getTsxInstance
  (JNIEnv *env, jclass clazz);

#ifdef __cplusplus
}
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_typeScript_TSLanguageTypeScript__Native_METHOD_SIGNATURES
#define _Included_com_itsaky_androidide_treesitter_typeScript_TSLanguageTypeScript__Native_METHOD_SIGNATURES

// Index of method getInstance of class com.itsaky.androidide.treesitter.typeScript.TSLanguageTypeScript.Native in _TSLanguageTypeScript_Native_METHODS array
#define TSLanguageTypeScript_Native_getInstance__ARR_IDX 0
#define TSLanguageTypeScript_Native_getTsxInstance__ARR_IDX 1

/*
 * Class:     com.itsaky.androidide.treesitter.typeScript.TSLanguageTypeScript.Native
 * Method:    getInstance
 * Signature: ()J
 */
static JNINativeMethod TSLanguageTypeScript_Native_getInstance= {
    .name = "getInstance",
    .signature = "()J",
    .fnPtr = nullptr
};
static JNINativeMethod TSLanguageTypeScript_Native_getTsxInstance = {
    .name = "getTsxInstance",
    .signature = "()J",
    .fnPtr = nullptr
};


// This function is called in order to set the actual
// implementations of the native methods defined in class 
// com/itsaky/androidide/treesitter/typeScript/TSLanguageTypeScript$Native
void TSLanguageTypeScript_Native_SetJniMethods(JNINativeMethod *methods, int count);

// Number of elements in _TSLanguageTypeScript_Native_METHODS
#define _TSLanguageTypeScript_Native_METHOD_COUNT 1
#define TSLanguageTypeScript_Native_METHOD_COUNT 2
// All native methods in class com/itsaky/androidide/treesitter/typeScript/TSLanguageTypeScript$Native
#define TSLanguageTypeScript_Native_DefMethodsArray \
    JNINativeMethod _TSLanguageTypeScript_Native_METHODS[] = { \
        TSLanguageTypeScript_Native_getInstance, \
        TSLanguageTypeScript_Native_getTsxInstance, \
    };

#ifndef SET_JNI_METHOD
#define SET_JNI_METHOD(_mths, _mth, _func) { \
    void *ptr = (void *)(&_func); \
    (_mths + _mth##__ARR_IDX)->fnPtr = ptr; \
    if (__TS_LOG_DEBUG == 1) { \
        LOGD(LOG_TAG, "SET_JNI_METHOD: %s to %p", _mth.name, ptr); \
        LOGD(LOG_TAG, "SET_JNI_METHOD: fnPtr = %p", _mths[_mth##__ARR_IDX].fnPtr); \
    } \
}
#endif


// Registers the native methods of class com/itsaky/androidide/treesitter/typeScript/TSLanguageTypeScript$Native with the given JNIEnv
#define TSLanguageTypeScript_Native_AutoRegisterNatives(_env) \
    int _TSLanguageTypeScript_Native_rc; \
    TSLanguageTypeScript_Native_SetJniMethods(&_TSLanguageTypeScript_Native_METHODS[0], _TSLanguageTypeScript_Native_METHOD_COUNT); \
    if (__TS_LOG_DEBUG == 1) { \
    for (int i = 0; i < _TSLanguageTypeScript_Native_METHOD_COUNT; ++i) { \
        JNINativeMethod mth = *(_TSLanguageTypeScript_Native_METHODS + i); \
        LOGD(LOG_TAG, "Register native method: '%s', '%s', '%p'", mth.name, mth.signature, mth.fnPtr); } \
    } \
    jclass _TSLanguageTypeScript_Native_class = _env->FindClass("com/itsaky/androidide/treesitter/typeScript/TSLanguageTypeScript$Native"); \
    if (_TSLanguageTypeScript_Native_class == NULL) { \
        LOGE(LOG_TAG, "Failed to find class com/itsaky/androidide/treesitter/typeScript/TSLanguageTypeScript$Native"); \
        return JNI_ERR; \
    } \
    _TSLanguageTypeScript_Native_rc = _env->RegisterNatives(_TSLanguageTypeScript_Native_class, _TSLanguageTypeScript_Native_METHODS, _TSLanguageTypeScript_Native_METHOD_COUNT); \
    if (_TSLanguageTypeScript_Native_rc != JNI_OK) { \
        LOGE(LOG_TAG, "Failed to register native methods for class 'com/itsaky/androidide/treesitter/typeScript/TSLanguageTypeScript$Native'. Result: %d", _TSLanguageTypeScript_Native_rc); \
        return _TSLanguageTypeScript_Native_rc; \
    }\


#endif
#endif