package com.itsaky.androidide.repository.dependencies.analyzer.internal

object DependencyDslConfigurations {
  val knownConfigurations: Set<String> =
      setOf(
          "classpath",
          "androidApis",
          "androidTestAnnotationProcessor",
          "androidTestApi",
          "androidTestApk",
          "androidTestCompile",
          "androidTestCompileOnly",
          "androidTestDebugAnnotationProcessor",
          "androidTestDebugApi",
          "androidTestDebugApk",
          "androidTestDebugCompile",
          "androidTestDebugCompileOnly",
          "androidTestDebugImplementation",
          "androidTestDebugProvided",
          "androidTestDebugRuntimeOnly",
          "androidTestDebugWearApp",
          "androidTestImplementation",
          "androidTestProvided",
          "androidTestRuntimeOnly",
          "androidTestUtil",
          "androidTestWearApp",
          "annotationProcessor",
          "api",
          "apk",
          "archives",
          "compile",
          "compileOnly",
          "coreLibraryDesugaring",
          "debugAnnotationProcessor",
          "debugApi",
          "debugApk",
          "debugCompile",
          "debugCompileOnly",
          "debugImplementation",
          "debugProvided",
          "debugRuntimeOnly",
          "debugWearApp",
          "default",
          "implementation",
          "kapt",
          "ksp",
          "lintChecks",
          "lintClassPath",
          "lintPublish",
          "provided",
          "releaseAnnotationProcessor",
          "releaseApi",
          "releaseApk",
          "releaseCompile",
          "releaseCompileOnly",
          "releaseImplementation",
          "releaseProvided",
          "releaseRuntimeOnly",
          "releaseWearApp",
          "runtimeOnly",
          "testAnnotationProcessor",
          "testApi",
          "testApk",
          "testCompile",
          "testCompileOnly",
          "testDebugAnnotationProcessor",
          "testDebugApi",
          "testDebugApk",
          "testDebugCompile",
          "testDebugCompileOnly",
          "testDebugImplementation",
          "testDebugProvided",
          "testDebugRuntimeOnly",
          "testDebugWearApp",
          "testImplementation",
          "testProvided",
          "testReleaseAnnotationProcessor",
          "testReleaseApi",
          "testReleaseApk",
          "testReleaseCompile",
          "testReleaseCompileOnly",
          "testReleaseImplementation",
          "testReleaseProvided",
          "testReleaseRuntimeOnly",
          "testReleaseWearApp",
          "testRuntimeOnly",
          "testWearApp",
          "wearApp",
      )

  fun isDependencyConfiguration(name: String): Boolean {
    if (name in knownConfigurations) return true
    return name.endsWith("Implementation") ||
        name.endsWith("Api") ||
        name.endsWith("CompileOnly") ||
        name.endsWith("RuntimeOnly")
  }
}
