// This file is automatically generated. DO NOT EDIT!

/*
 *  This file is part of android-tree-sitter.
 *
 *  android-tree-sitter library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  android-tree-sitter library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *  along with android-tree-sitter.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.itsaky.androidide.treesitter.typeScript;

import com.itsaky.androidide.treesitter.annotations.GenerateNativeHeaders;

import com.itsaky.androidide.treesitter.TSLanguage;
import com.itsaky.androidide.treesitter.TSLanguageCache;

/**
 * Tree Sitter for TypeScript.
 *
 * @author Akash Yadav
 */
public final class TSLanguageTypeScript {

    static {
        System.loadLibrary("tree-sitter-typeScript");
    }

    private TSLanguageTypeScript() {
        throw new UnsupportedOperationException();
    }

    /**
     * @deprecated Tree Sitter language instances are <code>static const</code> and hence, they do
     *     not change. The name of this method is misleading, use {@link
     *     TSLanguageTypeScript#getInstance()} instead.
     */
    @Deprecated
    public static TSLanguage newInstance() {
        return getInstance();
    }

    /**
     * Get the instance of the TypeScript language.
     *
     * @return The instance of the TypeScript language.
     */
    public static TSLanguage getInstance() {
        var language = TSLanguageCache.get("typeScript");
        if (language != null) {
            return language;
        }

        language = TSLanguage.create("typeScript", Native.getInstance());
        TSLanguageCache.cache("typeScript", language);
        return language;
    }

    public static TSLanguage getTsxInstance() {
        var language = TSLanguageCache.get("tsx");
        if (language != null) return language;
        language = TSLanguage.create("tsx", Native.getTsxInstance());
        TSLanguageCache.cache("tsx", language);
        return language;
    }

    @GenerateNativeHeaders(fileName = "typeScript")
    public static class Native {
        public static native long getInstance();

        public static native long getTsxInstance();
    }
}