rootProject.name = "language-lexer"

include(":toml")
include(":smali")
include(":groovy")
include(":cmake")
include(":css3")
include(":csv")
include(":ecmascript")
include(":html")
include(":javascript")
include(":json")
include(":json5")
include(":kotlin")
include(":kotlinformal")
include(":properties")
include(":protobuf3")
